{% set name = "pyzxing" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyzxing-{{ version }}.tar.gz
  sha256: 77087602f3ec5ccc3f20619f5f85246e02ff543b81c42c9b24dbc4a9f7f30e5c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.8,<3.13
    - setuptools
    - wheel
  run:
    - joblib
    - numpy
    - python >=3.8,<3.13
    - setuptools

test:
  imports:
    - pyzxing
    - src
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ChenjieXu/pyzxing
  summary: Python wrapper for ZXing Java library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ChenjieXu
