{% set name = "pyzxing" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyzxing-{{ version }}.tar.gz
  sha256: 099c4eab126b19e418835f3c89411d0d8522ad8efd5c81ce378c9110008cdde9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - joblib
    - numpy
    - python >=3.6
    - setuptools

test:
  imports:
    - pyzxing
    - src
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ChenjieXu/pyzxing
  summary: Python wrapper for ZXing Java library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ChenjieXu
